language: python
python:
  - "3.8.0"
before_install:
  - python -m pip install --upgrade pip
install:
  - pip install -r dev-requirements.txt
script:
  - python -m pylint bfxapi
  - python -m mypy bfxapi
  - python -m unittest bfxapi.tests
