language: python

before_install:
  - sudo apt-get update
  - sudo apt-get install python3
  - sudo apt-get install python3-pip
  - sudo python3 -m pip install --upgrade pip
# command to install dependencies
install:
  - python3 -m pip install -r requirements.txt --user
# command to run tests
script: python3 -m pylint --rcfile=pylint.rc bfxapi
