name: build

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest

    steps: 
      - uses: actions/checkout@v3
      - name: Set up Python 3.8
        uses: actions/setup-python@v4
        with:
          python-version: '3.8'
      - name: Install bitfinex-api-py's dependencies
        run: python -m pip install -r dev-requirements.txt
      - name: Run pre-commit hooks (see .pre-commit-config.yaml)
        uses: pre-commit/action@v3.0.1
      - name: Run mypy to ensure correct type hinting
        run: python -m mypy bfxapi
